export const LOAD_ORDER_SAMPLE_REQUEST = {
    name: '14.01.2026',
    mods: [
        {
            id: '2559634234',
            name: 'Lua For Barotrauma',
            category: 'LUA',
            above: [],
            requires: [],
        },
        {
            id: '2795927223',
            name: 'CsForBarotrauma',
            category: 'CS',
            above: [],
            requires: [],
        },
        {
            id: '3190189044',
            name: 'Neurotrauma',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3324062208',
            name: 'NT Cybernetics Enhanced',
            category: 'CONTENT',
            above: [],
            requires: ['3190189044'],
        },
        {
            id: '3478666406',
            name: 'NT Symbiote',
            category: 'CONTENT',
            above: [],
            requires: ['3190189044'],
        },
        {
            id: '3478084070',
            name: 'NT Surgery Plus',
            category: 'CONTENT',
            above: [],
            requires: ['3190189044'],
        },
        {
            id: '2913895660',
            name: 'NT Surgery Access Fix',
            category: 'PATCH',
            above: ['3190189044'],
            requires: ['3190189044'],
        },
        {
            id: '2936760984',
            name: 'Real Sonar',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '2965750397',
            name: 'Real Sonar Medical Item Recipes Patch for Neurotrauma',
            category: 'PATCH',
            above: ['2936760984', '3190189044'],
            requires: ['2936760984', '3190189044'],
        },
        {
            id: '2936086408',
            name: 'Extract It! Neurotrauma Patch',
            category: 'PATCH',
            above: ['3190189044'],
            requires: ['3190189044'],
        },
        {
            id: '3120380654',
            name: 'Immersive Repairs - Vanilla Welding Patch',
            category: 'PATCH',
            above: [],
            requires: [],
        },
        {
            id: '3153498101',
            name: 'Immersive Repairs - NT Cybernetics Compatibility Patch',
            category: 'PATCH',
            above: ['3324062208'],
            requires: ['3324062208'],
        },
        {
            id: '3645475713',
            name: 'Immersive Repairs without welding diving mask',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '2518816103',
            name: 'Barotraumatic',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3574385658',
            name: 'Gain XP for doing your job',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3590977394',
            name: 'Gain XP for doing your job RS Patch',
            category: 'PATCH',
            above: ['3574385658'],
            requires: ['3574385658'],
        },
        {
            id: '2902724993',
            name: 'Adapted Talent Trees V2',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3231293294',
            name: 'BetterHealthUI (Rework)',
            category: 'UI',
            above: [],
            requires: [],
        },
        {
            id: '2811300302',
            name: 'BetterFabricatorUI',
            category: 'UI',
            above: [],
            requires: [],
        },
        {
            id: '2891181800',
            name: 'Sort Container UI',
            category: 'UI',
            above: [],
            requires: [],
        },
        {
            id: '2989335840',
            name: 'Slots+ Deconstructor+Fabricator',
            category: 'UI',
            above: [],
            requires: [],
        },
        {
            id: '2701251094',
            name: 'Performance Fix',
            category: 'UTILITY',
            above: [],
            requires: [],
        },
        {
            id: '2658872348',
            name: 'Disconnect Kill And Stun Remover',
            category: 'UTILITY',
            above: [],
            requires: [],
        },
        {
            id: '2184257427',
            name: 'New Wrecks For Barotrauma (With sellable wrecks)',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '2772926011',
            name: 'Movable and Sellable Wrecks',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3325413761',
            name: '[EA-HI] With male+Neurotrauma',
            category: 'PATCH',
            above: ['3190189044'],
            requires: ['3190189044'],
        },
        {
            id: '3283095414',
            name: '[EA-HI] With Male Namelist Replacement Patch',
            category: 'PATCH',
            above: [],
            requires: [],
        },
        {
            id: '3127901589',
            name: '[EA-HI] \u6728\u536b\u4e8c\u840c\u5316\u6574\u5408\u5305 with male characters',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '3645470336',
            name: 'Wallaby S-82',
            category: 'CONTENT',
            above: [],
            requires: [],
        },
        {
            id: '2986079116',
            name: 'Total Russian Translation (TRT)',
            category: 'UI',
            above: [],
            requires: [],
        },
    ],
};
